import numpy as np
from trafficSim import *

sim = Simulation()

# Play with these
n = 20
a = -2
b = 12
l = 48

NUM_OF_ROADS = 36
VEHICLE_RATE = 80
STEPS_PER_UPDATE = 150  # Adjust this value to slow down the simulation

# Nodes
WEST_RIGHT_START = (-b-l, a)
WEST_LEFT_START = (-b-l, -a)

SOUTH_RIGHT_START = (a, b+l)
SOUTH_LEFT_START = (-a, b+l)

EAST_RIGHT_START = (b+l, -a)
EAST_LEFT_START = (b+l, a)

NORTH_RIGHT_START = (-a, -b-l)
NORTH_LEFT_START = (a, -b-l)

WEST_RIGHT = (-b, a)
WEST_LEFT =	(-b, -a)

SOUTH_RIGHT = (a, b)
SOUTH_LEFT = (-a, b)

EAST_RIGHT = (b, -a)
EAST_LEFT = (b, a)

NORTH_RIGHT = (-a, -b)
NORTH_LEFT = (a, -b)

WEST_RIGHT_START2 = (WEST_RIGHT_START[0], WEST_RIGHT_START[1] - 4)
WEST_LEFT_START2 = (WEST_LEFT_START[0], WEST_LEFT_START[1] + 4)

SOUTH_RIGHT_START2 = (SOUTH_RIGHT_START[0] - 4, SOUTH_RIGHT_START[1])
SOUTH_LEFT_START2 = (SOUTH_LEFT_START[0] + 4, SOUTH_LEFT_START[1])

EAST_RIGHT_START2 = (EAST_RIGHT_START[0], EAST_RIGHT_START[1] + 4)
EAST_LEFT_START2 = (EAST_LEFT_START[0], EAST_LEFT_START[1] - 4)

NORTH_RIGHT_START2 = (NORTH_RIGHT_START[0] + 4, NORTH_RIGHT_START[1])
NORTH_LEFT_START2 = (NORTH_LEFT_START[0] - 4, NORTH_LEFT_START[1])

WEST_RIGHT_START3 = (WEST_RIGHT_START[0], WEST_RIGHT_START[1] - 8)
WEST_LEFT_START3 = (WEST_LEFT_START[0], WEST_LEFT_START[1] + 8)

SOUTH_RIGHT_START3 = (SOUTH_RIGHT_START[0] - 8, SOUTH_RIGHT_START[1])
SOUTH_LEFT_START3 = (SOUTH_LEFT_START[0] + 8, SOUTH_LEFT_START[1])

EAST_RIGHT_START3 = (EAST_RIGHT_START[0], EAST_RIGHT_START[1] + 8)
EAST_LEFT_START3 = (EAST_LEFT_START[0], EAST_LEFT_START[1] - 8)

NORTH_RIGHT_START3 = (NORTH_RIGHT_START[0] + 8, NORTH_RIGHT_START[1])
NORTH_LEFT_START3 = (NORTH_LEFT_START[0] - 8, NORTH_LEFT_START[1])

WEST_RIGHT2 = (WEST_RIGHT[0], WEST_RIGHT[1] - 4)
WEST_LEFT2 =	(WEST_LEFT[0], WEST_LEFT[1] + 4)

SOUTH_RIGHT2 = (SOUTH_RIGHT[0] - 4, SOUTH_RIGHT[1])
SOUTH_LEFT2 = (SOUTH_LEFT[0] + 4, SOUTH_LEFT[1])

EAST_RIGHT2 = (EAST_RIGHT[0], EAST_RIGHT[1] + 4)
EAST_LEFT2 = (EAST_LEFT[0], EAST_LEFT[1] - 4)

NORTH_RIGHT2 = (NORTH_RIGHT[0] + 4, NORTH_RIGHT[1])
NORTH_LEFT2 = (NORTH_LEFT[0] - 4, NORTH_LEFT[1])

WEST_RIGHT3 = (WEST_RIGHT[0], WEST_RIGHT[1] - 8)
WEST_LEFT3 = (WEST_LEFT[0], WEST_LEFT[1] + 8)

SOUTH_RIGHT3 = (SOUTH_RIGHT[0] - 8, SOUTH_RIGHT[1])
SOUTH_LEFT3 = (SOUTH_LEFT[0] + 8, SOUTH_LEFT[1])

EAST_RIGHT3 = (EAST_RIGHT[0], EAST_RIGHT[1] + 8)
EAST_LEFT3 = (EAST_LEFT[0], EAST_LEFT[1] - 8)

NORTH_RIGHT3 = (NORTH_RIGHT[0] + 8, NORTH_RIGHT[1])
NORTH_LEFT3 = (NORTH_LEFT[0] - 8, NORTH_LEFT[1])

# Roads
WEST_INBOUND = (WEST_RIGHT_START, WEST_RIGHT)
SOUTH_INBOUND = (SOUTH_RIGHT_START, SOUTH_RIGHT)
EAST_INBOUND = (EAST_RIGHT_START, EAST_RIGHT)
NORTH_INBOUND = (NORTH_RIGHT_START, NORTH_RIGHT)

WEST_OUTBOUND = (WEST_LEFT, WEST_LEFT_START)
SOUTH_OUTBOUND = (SOUTH_LEFT, SOUTH_LEFT_START)
EAST_OUTBOUND = (EAST_LEFT, EAST_LEFT_START)
NORTH_OUTBOUND = (NORTH_LEFT, NORTH_LEFT_START)

WEST_STRAIGHT = (WEST_RIGHT, EAST_LEFT)
SOUTH_STRAIGHT = (SOUTH_RIGHT, NORTH_LEFT)
EAST_STRAIGHT = (EAST_RIGHT, WEST_LEFT)
NORTH_STRAIGHT = (NORTH_RIGHT, SOUTH_LEFT)

WEST_RIGHT_TURN = turn_road(WEST_RIGHT, SOUTH_LEFT, TURN_RIGHT, n)
WEST_LEFT_TURN = turn_road(WEST_RIGHT, NORTH_LEFT, TURN_LEFT, n)

SOUTH_RIGHT_TURN = turn_road(SOUTH_RIGHT, EAST_LEFT, TURN_RIGHT, n)
SOUTH_LEFT_TURN = turn_road(SOUTH_RIGHT, WEST_LEFT, TURN_LEFT, n)

EAST_RIGHT_TURN = turn_road(EAST_RIGHT, NORTH_LEFT, TURN_RIGHT, n)
EAST_LEFT_TURN = turn_road(EAST_RIGHT, SOUTH_LEFT, TURN_LEFT, n)

NORTH_RIGHT_TURN = turn_road(NORTH_RIGHT, WEST_LEFT, TURN_RIGHT, n)
NORTH_LEFT_TURN = turn_road(NORTH_RIGHT, EAST_LEFT, TURN_LEFT, n)

WEST_INBOUND2 = (WEST_RIGHT_START2, WEST_RIGHT2)
SOUTH_INBOUND2 = (SOUTH_RIGHT_START2, SOUTH_RIGHT2)
EAST_INBOUND2 = (EAST_RIGHT_START2, EAST_RIGHT2)
NORTH_INBOUND2 = (NORTH_RIGHT_START2, NORTH_RIGHT2)

WEST_OUTBOUND2 = (WEST_LEFT2, WEST_LEFT_START2)
SOUTH_OUTBOUND2 = (SOUTH_LEFT2, SOUTH_LEFT_START2)
EAST_OUTBOUND2 = (EAST_LEFT2, EAST_LEFT_START2)
NORTH_OUTBOUND2 = (NORTH_LEFT2, NORTH_LEFT_START2)

WEST_STRAIGHT2 = (WEST_RIGHT2, EAST_LEFT2)
SOUTH_STRAIGHT2 = (SOUTH_RIGHT2, NORTH_LEFT2)
EAST_STRAIGHT2 = (EAST_RIGHT2, WEST_LEFT2)
NORTH_STRAIGHT2 = (NORTH_RIGHT2, SOUTH_LEFT2)

WEST_RIGHT_TURN2 = turn_road(WEST_RIGHT2, SOUTH_LEFT2, TURN_RIGHT, n)
WEST_LEFT_TURN2 = turn_road(WEST_RIGHT2, NORTH_LEFT2, TURN_LEFT, n)

SOUTH_RIGHT_TURN2 = turn_road(SOUTH_RIGHT2, EAST_LEFT2, TURN_RIGHT, n)
SOUTH_LEFT_TURN2 = turn_road(SOUTH_RIGHT2, WEST_LEFT2, TURN_LEFT, n)

EAST_RIGHT_TURN2 = turn_road(EAST_RIGHT2, NORTH_LEFT2, TURN_RIGHT, n)
EAST_LEFT_TURN2 = turn_road(EAST_RIGHT2, SOUTH_LEFT2, TURN_LEFT, n)

NORTH_RIGHT_TURN2 = turn_road(NORTH_RIGHT2, WEST_LEFT2, TURN_RIGHT, n)
NORTH_LEFT_TURN2 = turn_road(NORTH_RIGHT2, EAST_LEFT2, TURN_LEFT, n)

WEST_INBOUND3 = (WEST_RIGHT_START3, WEST_RIGHT3)
SOUTH_INBOUND3 = (SOUTH_RIGHT_START3, SOUTH_RIGHT3)
EAST_INBOUND3 = (EAST_RIGHT_START3, EAST_RIGHT3)
NORTH_INBOUND3 = (NORTH_RIGHT_START3, NORTH_RIGHT3)

WEST_OUTBOUND3 = (WEST_LEFT3, WEST_LEFT_START3)
SOUTH_OUTBOUND3 = (SOUTH_LEFT3, SOUTH_LEFT_START3)
EAST_OUTBOUND3 = (EAST_LEFT3, EAST_LEFT_START3)
NORTH_OUTBOUND3 = (NORTH_LEFT3, NORTH_LEFT_START3)

WEST_STRAIGHT3 = (WEST_RIGHT3, EAST_LEFT3)
SOUTH_STRAIGHT3 = (SOUTH_RIGHT3, NORTH_LEFT3)
EAST_STRAIGHT3 = (EAST_RIGHT3, WEST_LEFT3)
NORTH_STRAIGHT3 = (NORTH_RIGHT3, SOUTH_LEFT3)

WEST_RIGHT_TURN3 = turn_road(WEST_RIGHT3, SOUTH_LEFT3, TURN_RIGHT, n)
WEST_LEFT_TURN3 = turn_road(WEST_RIGHT3, NORTH_LEFT3, TURN_LEFT, n)

SOUTH_RIGHT_TURN3 = turn_road(SOUTH_RIGHT3, EAST_LEFT3, TURN_RIGHT, n)
SOUTH_LEFT_TURN3 = turn_road(SOUTH_RIGHT3, WEST_LEFT3, TURN_LEFT, n)

EAST_RIGHT_TURN3 = turn_road(EAST_RIGHT3, NORTH_LEFT3, TURN_RIGHT, n)
EAST_LEFT_TURN3 = turn_road(EAST_RIGHT3, SOUTH_LEFT3, TURN_LEFT, n)

NORTH_RIGHT_TURN3 = turn_road(NORTH_RIGHT3, WEST_LEFT3, TURN_RIGHT, n)
NORTH_LEFT_TURN3 = turn_road(NORTH_RIGHT3, EAST_LEFT3, TURN_LEFT, n)

# Trying second intersection to the right of the original one
o2 = (2*b+l, 0)

b_WEST_RIGHT_START = (o2[0] + WEST_RIGHT_START[0], EAST_LEFT[1])
b_WEST_LEFT_START = (o2[0] + WEST_LEFT_START[0], EAST_RIGHT[1])

b_SOUTH_RIGHT_START = (o2[0] + SOUTH_RIGHT_START[0], SOUTH_RIGHT_START[1])
b_SOUTH_LEFT_START = (o2[0] + SOUTH_LEFT_START[0], SOUTH_LEFT_START[1])

b_EAST_RIGHT_START = (o2[0] + EAST_RIGHT_START[0], EAST_RIGHT_START[1])
b_EAST_LEFT_START = (o2[0] + EAST_LEFT_START[0], EAST_LEFT_START[1])

b_NORTH_RIGHT_START = (o2[0] + NORTH_RIGHT_START[0], NORTH_RIGHT_START[1])
b_NORTH_LEFT_START = (o2[0] + NORTH_LEFT_START[0], NORTH_LEFT_START[1])

b_WEST_RIGHT = (o2[0] + WEST_RIGHT[0], EAST_LEFT_START[1])
b_WEST_LEFT = (o2[0] + WEST_LEFT[0], EAST_RIGHT_START[1])

b_SOUTH_RIGHT = (o2[0] + SOUTH_RIGHT[0], SOUTH_RIGHT[1])
b_SOUTH_LEFT = (o2[0] + SOUTH_LEFT[0], SOUTH_LEFT[1])

b_EAST_RIGHT = (o2[0] + EAST_RIGHT[0], EAST_RIGHT[1])
b_EAST_LEFT = (o2[0] + EAST_LEFT[0], EAST_LEFT[1])

b_NORTH_RIGHT = (o2[0] + NORTH_RIGHT[0], NORTH_LEFT[1])
b_NORTH_LEFT = (o2[0] + NORTH_LEFT[0], NORTH_LEFT[1])

b_WEST_RIGHT_START2 = (b_WEST_RIGHT_START[0], b_WEST_RIGHT_START[1] - 4)
b_WEST_LEFT_START2 = (b_WEST_LEFT_START[0], b_WEST_LEFT_START[1] + 4)

b_SOUTH_RIGHT_START2 = (b_SOUTH_RIGHT_START[0] - 4, b_SOUTH_RIGHT_START[1])
b_SOUTH_LEFT_START2 = (b_SOUTH_LEFT_START[0] + 4, b_SOUTH_LEFT_START[1])

b_EAST_RIGHT_START2 = (b_EAST_RIGHT_START[0], b_EAST_RIGHT_START[1] + 4)
b_EAST_LEFT_START2 = (b_EAST_LEFT_START[0], b_EAST_LEFT_START[1] - 4)

b_NORTH_RIGHT_START2 = (b_NORTH_RIGHT_START[0] + 4, b_NORTH_RIGHT_START[1])
b_NORTH_LEFT_START2 = (b_NORTH_LEFT_START[0] - 4, b_NORTH_LEFT_START[1])

b_WEST_RIGHT_START3 = (b_WEST_RIGHT_START[0], b_WEST_RIGHT_START[1] - 8)
b_WEST_LEFT_START3 = (b_WEST_LEFT_START[0], b_WEST_LEFT_START[1] + 8)

b_SOUTH_RIGHT_START3 = (b_SOUTH_RIGHT_START[0] - 8, b_SOUTH_RIGHT_START[1])
b_SOUTH_LEFT_START3 = (b_SOUTH_LEFT_START[0] + 8, b_SOUTH_LEFT_START[1])

b_EAST_RIGHT_START3 = (b_EAST_RIGHT_START[0], b_EAST_RIGHT_START[1] + 8)
b_EAST_LEFT_START3 = (b_EAST_LEFT_START[0], b_EAST_LEFT_START[1] - 8)

b_NORTH_RIGHT_START3 = (b_NORTH_RIGHT_START[0] + 8, b_NORTH_RIGHT_START[1])
b_NORTH_LEFT_START3 = (b_NORTH_LEFT_START[0] - 8, b_NORTH_LEFT_START[1])

b_WEST_RIGHT2 = (b_WEST_RIGHT[0], b_WEST_RIGHT[1] - 4)
b_WEST_LEFT2 =	(b_WEST_LEFT[0], b_WEST_LEFT[1] + 4)

b_SOUTH_RIGHT2 = (b_SOUTH_RIGHT[0] - 4, b_SOUTH_RIGHT[1])
b_SOUTH_LEFT2 = (b_SOUTH_LEFT[0] + 4, b_SOUTH_LEFT[1])

b_EAST_RIGHT2 = (b_EAST_RIGHT[0], b_EAST_RIGHT[1] + 4)
b_EAST_LEFT2 = (b_EAST_LEFT[0], b_EAST_LEFT[1] - 4)

b_NORTH_RIGHT2 = (b_NORTH_RIGHT[0] + 4, b_NORTH_RIGHT[1])
b_NORTH_LEFT2 = (b_NORTH_LEFT[0] - 4, b_NORTH_LEFT[1])

b_WEST_RIGHT3 = (b_WEST_RIGHT[0], b_WEST_RIGHT[1] - 8)
b_WEST_LEFT3 =	(b_WEST_LEFT[0], b_WEST_LEFT[1] + 8)

b_SOUTH_RIGHT3 = (b_SOUTH_RIGHT[0] - 8, b_SOUTH_RIGHT[1])
b_SOUTH_LEFT3 = (b_SOUTH_LEFT[0] + 8, b_SOUTH_LEFT[1])

b_EAST_RIGHT3 = (b_EAST_RIGHT[0], b_EAST_RIGHT[1] + 8)
b_EAST_LEFT3 = (b_EAST_LEFT[0], b_EAST_LEFT[1] - 8)

b_NORTH_RIGHT3 = (b_NORTH_RIGHT[0] + 8, b_NORTH_RIGHT[1])
b_NORTH_LEFT3 = (b_NORTH_LEFT[0] - 8, b_NORTH_LEFT[1])

# Intersection b - Roads
b_WEST_INBOUND = (b_WEST_RIGHT_START, b_WEST_RIGHT)
b_SOUTH_INBOUND = (b_SOUTH_RIGHT_START, b_SOUTH_RIGHT)
b_EAST_INBOUND = (b_EAST_RIGHT_START, b_EAST_RIGHT)
b_NORTH_INBOUND = (b_NORTH_RIGHT_START, b_NORTH_RIGHT)

b_WEST_OUTBOUND = (b_WEST_LEFT, b_WEST_LEFT_START)
b_SOUTH_OUTBOUND = (b_SOUTH_LEFT, b_SOUTH_LEFT_START)
b_EAST_OUTBOUND = (b_EAST_LEFT, b_EAST_LEFT_START)
b_NORTH_OUTBOUND = (b_NORTH_LEFT, b_NORTH_LEFT_START)

b_WEST_STRAIGHT = (b_WEST_RIGHT, b_EAST_LEFT)
b_SOUTH_STRAIGHT = (b_SOUTH_RIGHT, b_NORTH_LEFT)
b_EAST_STRAIGHT = (b_EAST_RIGHT, b_WEST_LEFT)
b_NORTH_STRAIGHT = (b_NORTH_RIGHT, b_SOUTH_LEFT)

b_WEST_RIGHT_TURN = turn_road(b_WEST_RIGHT, b_SOUTH_LEFT, TURN_RIGHT, n)
b_WEST_LEFT_TURN = turn_road(b_WEST_RIGHT, b_NORTH_LEFT, TURN_LEFT, n)

b_SOUTH_RIGHT_TURN = turn_road(b_SOUTH_RIGHT, b_EAST_LEFT, TURN_RIGHT, n)
b_SOUTH_LEFT_TURN = turn_road(b_SOUTH_RIGHT, b_WEST_LEFT, TURN_LEFT, n)

b_EAST_RIGHT_TURN = turn_road(b_EAST_RIGHT, b_NORTH_LEFT, TURN_RIGHT, n)
b_EAST_LEFT_TURN = turn_road(b_EAST_RIGHT, b_SOUTH_LEFT, TURN_LEFT, n)

b_NORTH_RIGHT_TURN = turn_road(b_NORTH_RIGHT, b_WEST_LEFT, TURN_RIGHT, n)
b_NORTH_LEFT_TURN = turn_road(b_NORTH_RIGHT, b_EAST_LEFT, TURN_LEFT, n)

b_WEST_INBOUND2 = (b_WEST_RIGHT_START2, b_WEST_RIGHT2)
b_SOUTH_INBOUND2 = (b_SOUTH_RIGHT_START2, b_SOUTH_RIGHT2)
b_EAST_INBOUND2 = (b_EAST_RIGHT_START2, b_EAST_RIGHT2)
b_NORTH_INBOUND2 = (b_NORTH_RIGHT_START2, b_NORTH_RIGHT2)

b_WEST_OUTBOUND2 = (b_WEST_LEFT2, b_WEST_LEFT_START2)
b_SOUTH_OUTBOUND2 = (b_SOUTH_LEFT2, b_SOUTH_LEFT_START2)
b_EAST_OUTBOUND2 = (b_EAST_LEFT2, b_EAST_LEFT_START2)
b_NORTH_OUTBOUND2 = (b_NORTH_LEFT2, b_NORTH_LEFT_START2)

b_WEST_STRAIGHT2 = (b_WEST_RIGHT2, b_EAST_LEFT2)
b_SOUTH_STRAIGHT2 = (b_SOUTH_RIGHT2, b_NORTH_LEFT2)
b_EAST_STRAIGHT2 = (b_EAST_RIGHT2, b_WEST_LEFT2)
b_NORTH_STRAIGHT2 = (b_NORTH_RIGHT2, b_SOUTH_LEFT2)

b_WEST_RIGHT_TURN2 = turn_road(b_WEST_RIGHT2, b_SOUTH_LEFT2, TURN_RIGHT, n)
b_WEST_LEFT_TURN2 = turn_road(b_WEST_RIGHT2, b_NORTH_LEFT2, TURN_LEFT, n)

b_SOUTH_RIGHT_TURN2 = turn_road(b_SOUTH_RIGHT2, b_EAST_LEFT2, TURN_RIGHT, n)
b_SOUTH_LEFT_TURN2 = turn_road(b_SOUTH_RIGHT2, b_WEST_LEFT2, TURN_LEFT, n)

b_EAST_RIGHT_TURN2 = turn_road(b_EAST_RIGHT2, b_NORTH_LEFT2, TURN_RIGHT, n)
b_EAST_LEFT_TURN2 = turn_road(b_EAST_RIGHT2, b_SOUTH_LEFT2, TURN_LEFT, n)

b_NORTH_RIGHT_TURN2 = turn_road(b_NORTH_RIGHT2, b_WEST_LEFT2, TURN_RIGHT, n)
b_NORTH_LEFT_TURN2 = turn_road(b_NORTH_RIGHT2, b_EAST_LEFT2, TURN_LEFT, n)

b_WEST_INBOUND3 = (b_WEST_RIGHT_START3, b_WEST_RIGHT3)
b_SOUTH_INBOUND3 = (b_SOUTH_RIGHT_START3, b_SOUTH_RIGHT3)
b_EAST_INBOUND3 = (b_EAST_RIGHT_START3, b_EAST_RIGHT3)
b_NORTH_INBOUND3 = (b_NORTH_RIGHT_START3, b_NORTH_RIGHT3)

b_WEST_OUTBOUND3 = (b_WEST_LEFT3, b_WEST_LEFT_START3)
b_SOUTH_OUTBOUND3 = (b_SOUTH_LEFT3, b_SOUTH_LEFT_START3)
b_EAST_OUTBOUND3 = (b_EAST_LEFT3, b_EAST_LEFT_START3)
b_NORTH_OUTBOUND3 = (b_NORTH_LEFT3, b_NORTH_LEFT_START3)

b_WEST_STRAIGHT3 = (b_WEST_RIGHT3, b_EAST_LEFT3)
b_SOUTH_STRAIGHT3 = (b_SOUTH_RIGHT3, b_NORTH_LEFT3)
b_EAST_STRAIGHT3 = (b_EAST_RIGHT3, b_WEST_LEFT3)
b_NORTH_STRAIGHT3 = (b_NORTH_RIGHT3, b_SOUTH_LEFT3)

b_WEST_RIGHT_TURN3 = turn_road(b_WEST_RIGHT3, b_SOUTH_LEFT3, TURN_RIGHT, n)
b_WEST_LEFT_TURN3 = turn_road(b_WEST_RIGHT3, b_NORTH_LEFT3, TURN_LEFT, n)

b_SOUTH_RIGHT_TURN3 = turn_road(b_SOUTH_RIGHT3, b_EAST_LEFT3, TURN_RIGHT, n)
b_SOUTH_LEFT_TURN3 = turn_road(b_SOUTH_RIGHT3, b_WEST_LEFT3, TURN_LEFT, n)

b_EAST_RIGHT_TURN3 = turn_road(b_EAST_RIGHT3, b_NORTH_LEFT3, TURN_RIGHT, n)
b_EAST_LEFT_TURN3 = turn_road(b_EAST_RIGHT3, b_SOUTH_LEFT3, TURN_LEFT, n)

b_NORTH_RIGHT_TURN3 = turn_road(b_NORTH_RIGHT3, b_WEST_LEFT3, TURN_RIGHT, n)
b_NORTH_LEFT_TURN3 = turn_road(b_NORTH_RIGHT3, b_EAST_LEFT3, TURN_LEFT, n)

# Trying third intersection to the right of the original one
o3 = (2*b - 2* l, 0)

c_WEST_RIGHT_START = (o3[0] + WEST_RIGHT_START[0], EAST_LEFT[1])
c_WEST_LEFT_START = (o3[0] + WEST_LEFT_START[0], EAST_RIGHT[1])

c_SOUTH_RIGHT_START = (o3[0] + SOUTH_RIGHT_START[0], SOUTH_RIGHT_START[1])
c_SOUTH_LEFT_START = (o3[0] + SOUTH_LEFT_START[0], SOUTH_LEFT_START[1])

c_EAST_RIGHT_START = (o3[0] + EAST_RIGHT_START[0], EAST_RIGHT_START[1])
c_EAST_LEFT_START = (o3[0] + EAST_LEFT_START[0], EAST_LEFT_START[1])

c_NORTH_RIGHT_START = (o3[0] + NORTH_RIGHT_START[0], NORTH_RIGHT_START[1])
c_NORTH_LEFT_START = (o3[0] + NORTH_LEFT_START[0], NORTH_LEFT_START[1])

c_WEST_RIGHT = (o3[0] + WEST_RIGHT[0], EAST_LEFT_START[1])
c_WEST_LEFT = (o3[0] + WEST_LEFT[0], EAST_RIGHT_START[1])

c_SOUTH_RIGHT = (o3[0] + SOUTH_RIGHT[0], SOUTH_RIGHT[1])
c_SOUTH_LEFT = (o3[0] + SOUTH_LEFT[0], SOUTH_LEFT[1])

c_EAST_RIGHT = (o3[0] + EAST_RIGHT[0], EAST_RIGHT[1])
c_EAST_LEFT = (o3[0] + EAST_LEFT[0], EAST_LEFT[1])

c_NORTH_RIGHT = (o3[0] + NORTH_RIGHT[0], NORTH_LEFT[1])
c_NORTH_LEFT = (o3[0] + NORTH_LEFT[0], NORTH_LEFT[1])

c_WEST_RIGHT_START2 = (c_WEST_RIGHT_START[0], c_WEST_RIGHT_START[1] - 4)
c_WEST_LEFT_START2 = (c_WEST_LEFT_START[0], c_WEST_LEFT_START[1] + 4)

c_SOUTH_RIGHT_START2 = (c_SOUTH_RIGHT_START[0] - 4, c_SOUTH_RIGHT_START[1])
c_SOUTH_LEFT_START2 = (c_SOUTH_LEFT_START[0] + 4, c_SOUTH_LEFT_START[1])

c_EAST_RIGHT_START2 = (c_EAST_RIGHT_START[0], c_EAST_RIGHT_START[1] + 4)
c_EAST_LEFT_START2 = (c_EAST_LEFT_START[0], c_EAST_LEFT_START[1] - 4)

c_NORTH_RIGHT_START2 = (c_NORTH_RIGHT_START[0] + 4, c_NORTH_RIGHT_START[1])
c_NORTH_LEFT_START2 = (c_NORTH_LEFT_START[0] - 4, c_NORTH_LEFT_START[1])

c_WEST_RIGHT_START3 = (c_WEST_RIGHT_START[0], c_WEST_RIGHT_START[1] - 8)
c_WEST_LEFT_START3 = (c_WEST_LEFT_START[0], c_WEST_LEFT_START[1] + 8)

c_SOUTH_RIGHT_START3 = (c_SOUTH_RIGHT_START[0] - 8, c_SOUTH_RIGHT_START[1])
c_SOUTH_LEFT_START3 = (c_SOUTH_LEFT_START[0] + 8, c_SOUTH_LEFT_START[1])

c_EAST_RIGHT_START3 = (c_EAST_RIGHT_START[0], c_EAST_RIGHT_START[1] + 8)
c_EAST_LEFT_START3 = (c_EAST_LEFT_START[0], c_EAST_LEFT_START[1] - 8)

c_NORTH_RIGHT_START3 = (c_NORTH_RIGHT_START[0] + 8, c_NORTH_RIGHT_START[1])
c_NORTH_LEFT_START3 = (c_NORTH_LEFT_START[0] - 8, c_NORTH_LEFT_START[1])

c_WEST_RIGHT2 = (c_WEST_RIGHT[0], c_WEST_RIGHT[1] - 4)
c_WEST_LEFT2 =	(c_WEST_LEFT[0], c_WEST_LEFT[1] + 4)

c_SOUTH_RIGHT2 = (c_SOUTH_RIGHT[0] - 4, c_SOUTH_RIGHT[1])
c_SOUTH_LEFT2 = (c_SOUTH_LEFT[0] + 4, c_SOUTH_LEFT[1])

c_EAST_RIGHT2 = (c_EAST_RIGHT[0], c_EAST_RIGHT[1] + 4)
c_EAST_LEFT2 = (c_EAST_LEFT[0], c_EAST_LEFT[1] - 4)

c_NORTH_RIGHT2 = (c_NORTH_RIGHT[0] + 4, c_NORTH_RIGHT[1])
c_NORTH_LEFT2 = (c_NORTH_LEFT[0] - 4, c_NORTH_LEFT[1])

c_WEST_RIGHT3 = (c_WEST_RIGHT[0], c_WEST_RIGHT[1] - 8)
c_WEST_LEFT3 =	(c_WEST_LEFT[0], c_WEST_LEFT[1] + 8)

c_SOUTH_RIGHT3 = (c_SOUTH_RIGHT[0] - 8, c_SOUTH_RIGHT[1])
c_SOUTH_LEFT3 = (c_SOUTH_LEFT[0] + 8, c_SOUTH_LEFT[1])

c_EAST_RIGHT3 = (c_EAST_RIGHT[0], c_EAST_RIGHT[1] + 8)
c_EAST_LEFT3 = (c_EAST_LEFT[0], c_EAST_LEFT[1] - 8)

c_NORTH_RIGHT3 = (c_NORTH_RIGHT[0] + 8, c_NORTH_RIGHT[1])
c_NORTH_LEFT3 = (c_NORTH_LEFT[0] - 8, c_NORTH_LEFT[1])

# Intersection c - Roads
c_WEST_INBOUND = (c_WEST_RIGHT_START, c_WEST_RIGHT)
c_SOUTH_INBOUND = (c_SOUTH_RIGHT_START, c_SOUTH_RIGHT)
c_EAST_INBOUND = (c_EAST_RIGHT_START, c_EAST_RIGHT)
c_NORTH_INBOUND = (c_NORTH_RIGHT_START, c_NORTH_RIGHT)

c_WEST_OUTBOUND = (c_WEST_LEFT, c_WEST_LEFT_START)
c_SOUTH_OUTBOUND = (c_SOUTH_LEFT, c_SOUTH_LEFT_START)
c_EAST_OUTBOUND = (c_EAST_LEFT, c_EAST_LEFT_START)
c_NORTH_OUTBOUND = (c_NORTH_LEFT, c_NORTH_LEFT_START)

c_WEST_STRAIGHT = (c_WEST_RIGHT, c_EAST_LEFT)
c_SOUTH_STRAIGHT = (c_SOUTH_RIGHT, c_NORTH_LEFT)
c_EAST_STRAIGHT = (c_EAST_RIGHT, c_WEST_LEFT)
c_NORTH_STRAIGHT = (c_NORTH_RIGHT, c_SOUTH_LEFT)

c_WEST_RIGHT_TURN = turn_road(c_WEST_RIGHT, c_SOUTH_LEFT, TURN_RIGHT, n)
c_WEST_LEFT_TURN = turn_road(c_WEST_RIGHT, c_NORTH_LEFT, TURN_LEFT, n)

c_SOUTH_RIGHT_TURN = turn_road(c_SOUTH_RIGHT, c_EAST_LEFT, TURN_RIGHT, n)
c_SOUTH_LEFT_TURN = turn_road(c_SOUTH_RIGHT, c_WEST_LEFT, TURN_LEFT, n)

c_EAST_RIGHT_TURN = turn_road(c_EAST_RIGHT, c_NORTH_LEFT, TURN_RIGHT, n)
c_EAST_LEFT_TURN = turn_road(c_EAST_RIGHT, c_SOUTH_LEFT, TURN_LEFT, n)

c_NORTH_RIGHT_TURN = turn_road(c_NORTH_RIGHT, c_WEST_LEFT, TURN_RIGHT, n)
c_NORTH_LEFT_TURN = turn_road(c_NORTH_RIGHT, c_EAST_LEFT, TURN_LEFT, n)

c_WEST_INBOUND2 = (c_WEST_RIGHT_START2, c_WEST_RIGHT2)
c_SOUTH_INBOUND2 = (c_SOUTH_RIGHT_START2, c_SOUTH_RIGHT2)
c_EAST_INBOUND2 = (c_EAST_RIGHT_START2, c_EAST_RIGHT2)
c_NORTH_INBOUND2 = (c_NORTH_RIGHT_START2, c_NORTH_RIGHT2)

c_WEST_OUTBOUND2 = (c_WEST_LEFT2, c_WEST_LEFT_START2)
c_SOUTH_OUTBOUND2 = (c_SOUTH_LEFT2, c_SOUTH_LEFT_START2)
c_EAST_OUTBOUND2 = (c_EAST_LEFT2, c_EAST_LEFT_START2)
c_NORTH_OUTBOUND2 = (c_NORTH_LEFT2, c_NORTH_LEFT_START2)

c_WEST_STRAIGHT2 = (c_WEST_RIGHT2, c_EAST_LEFT2)
c_SOUTH_STRAIGHT2 = (c_SOUTH_RIGHT2, c_NORTH_LEFT2)
c_EAST_STRAIGHT2 = (c_EAST_RIGHT2, c_WEST_LEFT2)
c_NORTH_STRAIGHT2 = (c_NORTH_RIGHT2, c_SOUTH_LEFT2)

c_WEST_RIGHT_TURN2 = turn_road(c_WEST_RIGHT2, c_SOUTH_LEFT2, TURN_RIGHT, n)
c_WEST_LEFT_TURN2 = turn_road(c_WEST_RIGHT2, c_NORTH_LEFT2, TURN_LEFT, n)

c_SOUTH_RIGHT_TURN2 = turn_road(c_SOUTH_RIGHT2, c_EAST_LEFT2, TURN_RIGHT, n)
c_SOUTH_LEFT_TURN2 = turn_road(c_SOUTH_RIGHT2, c_WEST_LEFT2, TURN_LEFT, n)

c_EAST_RIGHT_TURN2 = turn_road(c_EAST_RIGHT2, c_NORTH_LEFT2, TURN_RIGHT, n)
c_EAST_LEFT_TURN2 = turn_road(c_EAST_RIGHT2, c_SOUTH_LEFT2, TURN_LEFT, n)

c_NORTH_RIGHT_TURN2 = turn_road(c_NORTH_RIGHT2, c_WEST_LEFT2, TURN_RIGHT, n)
c_NORTH_LEFT_TURN2 = turn_road(c_NORTH_RIGHT2, c_EAST_LEFT2, TURN_LEFT, n)

c_WEST_INBOUND3 = (c_WEST_RIGHT_START3, c_WEST_RIGHT3)
c_SOUTH_INBOUND3 = (c_SOUTH_RIGHT_START3, c_SOUTH_RIGHT3)
c_EAST_INBOUND3 = (c_EAST_RIGHT_START3, c_EAST_RIGHT3)
c_NORTH_INBOUND3 = (c_NORTH_RIGHT_START3, c_NORTH_RIGHT3)

c_WEST_OUTBOUND3 = (c_WEST_LEFT3, c_WEST_LEFT_START3)
c_SOUTH_OUTBOUND3 = (c_SOUTH_LEFT3, c_SOUTH_LEFT_START3)
c_EAST_OUTBOUND3 = (c_EAST_LEFT3, c_EAST_LEFT_START3)
c_NORTH_OUTBOUND3 = (c_NORTH_LEFT3, c_NORTH_LEFT_START3)

c_WEST_STRAIGHT3 = (c_WEST_RIGHT3, c_EAST_LEFT3)
c_SOUTH_STRAIGHT3 = (c_SOUTH_RIGHT3, c_NORTH_LEFT3)
c_EAST_STRAIGHT3 = (c_EAST_RIGHT3, c_WEST_LEFT3)
c_NORTH_STRAIGHT3 = (c_NORTH_RIGHT3, c_SOUTH_LEFT3)

c_WEST_RIGHT_TURN3 = turn_road(c_WEST_RIGHT3, c_SOUTH_LEFT3, TURN_RIGHT, n)
c_WEST_LEFT_TURN3 = turn_road(c_WEST_RIGHT3, c_NORTH_LEFT3, TURN_LEFT, n)

c_SOUTH_RIGHT_TURN3 = turn_road(c_SOUTH_RIGHT3, c_EAST_LEFT3, TURN_RIGHT, n)
c_SOUTH_LEFT_TURN3 = turn_road(c_SOUTH_RIGHT3, c_WEST_LEFT3, TURN_LEFT, n)

c_EAST_RIGHT_TURN3 = turn_road(c_EAST_RIGHT3, c_NORTH_LEFT3, TURN_RIGHT, n)
c_EAST_LEFT_TURN3 = turn_road(c_EAST_RIGHT3, c_SOUTH_LEFT3, TURN_LEFT, n)

c_NORTH_RIGHT_TURN3 = turn_road(c_NORTH_RIGHT3, c_WEST_LEFT3, TURN_RIGHT, n)
c_NORTH_LEFT_TURN3 = turn_road(c_NORTH_RIGHT3, c_EAST_LEFT3, TURN_LEFT, n)

# Trying third intersection to the right of the original one
o4 = ( 2*b - 2 * l, 0)

d_WEST_RIGHT_START = ( WEST_RIGHT_START[0], EAST_LEFT[1]+ o4[0] )
d_WEST_LEFT_START = ( WEST_LEFT_START[0], EAST_RIGHT[1]+ o4[0] )

d_SOUTH_RIGHT_START = ( SOUTH_RIGHT_START[0], SOUTH_RIGHT_START[1]+ o4[0] )
d_SOUTH_LEFT_START = ( SOUTH_LEFT_START[0], SOUTH_LEFT_START[1]+ o4[0] )

d_EAST_RIGHT_START = ( EAST_RIGHT_START[0], EAST_RIGHT_START[1]+ o4[0] )
d_EAST_LEFT_START = ( EAST_LEFT_START[0], EAST_LEFT_START[1]+ o4[0] )

d_NORTH_RIGHT_START = ( NORTH_RIGHT_START[0], NORTH_RIGHT_START[1]+ o4[0] )
d_NORTH_LEFT_START = ( NORTH_LEFT_START[0], NORTH_LEFT_START[1]+ o4[0] )

d_WEST_RIGHT = ( WEST_RIGHT[0], EAST_LEFT_START[1]+ o4[0] )
d_WEST_LEFT = ( WEST_LEFT[0], EAST_RIGHT_START[1]+ o4[0] )

d_SOUTH_RIGHT = ( SOUTH_RIGHT[0], SOUTH_RIGHT[1]+ o4[0] )
d_SOUTH_LEFT = ( SOUTH_LEFT[0], SOUTH_LEFT[1]+ o4[0] )

d_EAST_RIGHT = ( EAST_RIGHT[0], EAST_RIGHT[1]+ o4[0] )
d_EAST_LEFT = ( EAST_LEFT[0], EAST_LEFT[1]+ o4[0] )

d_NORTH_RIGHT = ( NORTH_RIGHT[0], NORTH_LEFT[1]+ o4[0] )
d_NORTH_LEFT = ( NORTH_LEFT[0], NORTH_LEFT[1]+ o4[0] )

d_WEST_RIGHT_START2 = (d_WEST_RIGHT_START[0], d_WEST_RIGHT_START[1] - 4)
d_WEST_LEFT_START2 = (d_WEST_LEFT_START[0], d_WEST_LEFT_START[1] + 4)

d_SOUTH_RIGHT_START2 = (d_SOUTH_RIGHT_START[0] - 4, d_SOUTH_RIGHT_START[1])
d_SOUTH_LEFT_START2 = (d_SOUTH_LEFT_START[0] + 4, d_SOUTH_LEFT_START[1])

d_EAST_RIGHT_START2 = (d_EAST_RIGHT_START[0], d_EAST_RIGHT_START[1] + 4)
d_EAST_LEFT_START2 = (d_EAST_LEFT_START[0], d_EAST_LEFT_START[1] - 4)

d_NORTH_RIGHT_START2 = (d_NORTH_RIGHT_START[0] + 4, d_NORTH_RIGHT_START[1])
d_NORTH_LEFT_START2 = (d_NORTH_LEFT_START[0] - 4, d_NORTH_LEFT_START[1])

d_WEST_RIGHT_START3 = (d_WEST_RIGHT_START[0], d_WEST_RIGHT_START[1] - 8)
d_WEST_LEFT_START3 = (d_WEST_LEFT_START[0], d_WEST_LEFT_START[1] + 8)

d_SOUTH_RIGHT_START3 = (d_SOUTH_RIGHT_START[0] - 8, d_SOUTH_RIGHT_START[1])
d_SOUTH_LEFT_START3 = (d_SOUTH_LEFT_START[0] + 8, d_SOUTH_LEFT_START[1])

d_EAST_RIGHT_START3 = (d_EAST_RIGHT_START[0], d_EAST_RIGHT_START[1] + 8)
d_EAST_LEFT_START3 = (d_EAST_LEFT_START[0], d_EAST_LEFT_START[1] - 8)

d_NORTH_RIGHT_START3 = (d_NORTH_RIGHT_START[0] + 8, d_NORTH_RIGHT_START[1])
d_NORTH_LEFT_START3 = (d_NORTH_LEFT_START[0] - 8, d_NORTH_LEFT_START[1])

d_WEST_RIGHT2 = (d_WEST_RIGHT[0], d_WEST_RIGHT[1] - 4)
d_WEST_LEFT2 =	(d_WEST_LEFT[0], d_WEST_LEFT[1] + 4)

d_SOUTH_RIGHT2 = (d_SOUTH_RIGHT[0] - 4, d_SOUTH_RIGHT[1])
d_SOUTH_LEFT2 = (d_SOUTH_LEFT[0] + 4, d_SOUTH_LEFT[1])

d_EAST_RIGHT2 = (d_EAST_RIGHT[0], d_EAST_RIGHT[1] + 4)
d_EAST_LEFT2 = (d_EAST_LEFT[0], d_EAST_LEFT[1] - 4)

d_NORTH_RIGHT2 = (d_NORTH_RIGHT[0] + 4, d_NORTH_RIGHT[1])
d_NORTH_LEFT2 = (d_NORTH_LEFT[0] - 4, d_NORTH_LEFT[1])

d_WEST_RIGHT3 = (d_WEST_RIGHT[0], d_WEST_RIGHT[1] - 8)
d_WEST_LEFT3 =	(d_WEST_LEFT[0], d_WEST_LEFT[1] + 8)

d_SOUTH_RIGHT3 = (d_SOUTH_RIGHT[0] - 8, d_SOUTH_RIGHT[1])
d_SOUTH_LEFT3 = (d_SOUTH_LEFT[0] + 8, d_SOUTH_LEFT[1])

d_EAST_RIGHT3 = (d_EAST_RIGHT[0], d_EAST_RIGHT[1] + 8)
d_EAST_LEFT3 = (d_EAST_LEFT[0], d_EAST_LEFT[1] - 8)

d_NORTH_RIGHT3 = (d_NORTH_RIGHT[0] + 8, d_NORTH_RIGHT[1])
d_NORTH_LEFT3 = (d_NORTH_LEFT[0] - 8, d_NORTH_LEFT[1])

# Intersection d - Roads
d_WEST_INBOUND = (d_WEST_RIGHT_START, d_WEST_RIGHT)
d_SOUTH_INBOUND = (d_SOUTH_RIGHT_START, d_SOUTH_RIGHT)
d_EAST_INBOUND = (d_EAST_RIGHT_START, d_EAST_RIGHT)
d_NORTH_INBOUND = (d_NORTH_RIGHT_START, d_NORTH_RIGHT)

d_WEST_OUTBOUND = (d_WEST_LEFT, d_WEST_LEFT_START)
d_SOUTH_OUTBOUND = (d_SOUTH_LEFT, d_SOUTH_LEFT_START)
d_EAST_OUTBOUND = (d_EAST_LEFT, d_EAST_LEFT_START)
d_NORTH_OUTBOUND = (d_NORTH_LEFT, d_NORTH_LEFT_START)

d_WEST_STRAIGHT = (d_WEST_RIGHT, d_EAST_LEFT)
d_SOUTH_STRAIGHT = (d_SOUTH_RIGHT, d_NORTH_LEFT)
d_EAST_STRAIGHT = (d_EAST_RIGHT, d_WEST_LEFT)
d_NORTH_STRAIGHT = (d_NORTH_RIGHT, d_SOUTH_LEFT)

d_WEST_RIGHT_TURN = turn_road(d_WEST_RIGHT, d_SOUTH_LEFT, TURN_RIGHT, n)
d_WEST_LEFT_TURN = turn_road(d_WEST_RIGHT, d_NORTH_LEFT, TURN_LEFT, n)

d_SOUTH_RIGHT_TURN = turn_road(d_SOUTH_RIGHT, d_EAST_LEFT, TURN_RIGHT, n)
d_SOUTH_LEFT_TURN = turn_road(d_SOUTH_RIGHT, d_WEST_LEFT, TURN_LEFT, n)

d_EAST_RIGHT_TURN = turn_road(d_EAST_RIGHT, d_NORTH_LEFT, TURN_RIGHT, n)
d_EAST_LEFT_TURN = turn_road(d_EAST_RIGHT, d_SOUTH_LEFT, TURN_LEFT, n)

d_NORTH_RIGHT_TURN = turn_road(d_NORTH_RIGHT, d_WEST_LEFT, TURN_RIGHT, n)
d_NORTH_LEFT_TURN = turn_road(d_NORTH_RIGHT, d_EAST_LEFT, TURN_LEFT, n)

d_WEST_INBOUND2 = (d_WEST_RIGHT_START2, d_WEST_RIGHT2)
d_SOUTH_INBOUND2 = (d_SOUTH_RIGHT_START2, d_SOUTH_RIGHT2)
d_EAST_INBOUND2 = (d_EAST_RIGHT_START2, d_EAST_RIGHT2)
d_NORTH_INBOUND2 = (d_NORTH_RIGHT_START2, d_NORTH_RIGHT2)

d_WEST_OUTBOUND2 = (d_WEST_LEFT2, d_WEST_LEFT_START2)
d_SOUTH_OUTBOUND2 = (d_SOUTH_LEFT2, d_SOUTH_LEFT_START2)
d_EAST_OUTBOUND2 = (d_EAST_LEFT2, d_EAST_LEFT_START2)
d_NORTH_OUTBOUND2 = (d_NORTH_LEFT2, d_NORTH_LEFT_START2)

d_WEST_STRAIGHT2 = (d_WEST_RIGHT2, d_EAST_LEFT2)
d_SOUTH_STRAIGHT2 = (d_SOUTH_RIGHT2, d_NORTH_LEFT2)
d_EAST_STRAIGHT2 = (d_EAST_RIGHT2, d_WEST_LEFT2)
d_NORTH_STRAIGHT2 = (d_NORTH_RIGHT2, d_SOUTH_LEFT2)

d_WEST_RIGHT_TURN2 = turn_road(d_WEST_RIGHT2, d_SOUTH_LEFT2, TURN_RIGHT, n)
d_WEST_LEFT_TURN2 = turn_road(d_WEST_RIGHT2, d_NORTH_LEFT2, TURN_LEFT, n)

d_SOUTH_RIGHT_TURN2 = turn_road(d_SOUTH_RIGHT2, d_EAST_LEFT2, TURN_RIGHT, n)
d_SOUTH_LEFT_TURN2 = turn_road(d_SOUTH_RIGHT2, d_WEST_LEFT2, TURN_LEFT, n)

d_EAST_RIGHT_TURN2 = turn_road(d_EAST_RIGHT2, d_NORTH_LEFT2, TURN_RIGHT, n)
d_EAST_LEFT_TURN2 = turn_road(d_EAST_RIGHT2, d_SOUTH_LEFT2, TURN_LEFT, n)

d_NORTH_RIGHT_TURN2 = turn_road(d_NORTH_RIGHT2, d_WEST_LEFT2, TURN_RIGHT, n)
d_NORTH_LEFT_TURN2 = turn_road(d_NORTH_RIGHT2, d_EAST_LEFT2, TURN_LEFT, n)

d_WEST_INBOUND3 = (d_WEST_RIGHT_START3, d_WEST_RIGHT3)
d_SOUTH_INBOUND3 = (d_SOUTH_RIGHT_START3, d_SOUTH_RIGHT3)
d_EAST_INBOUND3 = (d_EAST_RIGHT_START3, d_EAST_RIGHT3)
d_NORTH_INBOUND3 = (d_NORTH_RIGHT_START3, d_NORTH_RIGHT3)

d_WEST_OUTBOUND3 = (d_WEST_LEFT3, d_WEST_LEFT_START3)
d_SOUTH_OUTBOUND3 = (d_SOUTH_LEFT3, d_SOUTH_LEFT_START3)
d_EAST_OUTBOUND3 = (d_EAST_LEFT3, d_EAST_LEFT_START3)
d_NORTH_OUTBOUND3 = (d_NORTH_LEFT3, d_NORTH_LEFT_START3)

d_WEST_STRAIGHT3 = (d_WEST_RIGHT3, d_EAST_LEFT3)
d_SOUTH_STRAIGHT3 = (d_SOUTH_RIGHT3, d_NORTH_LEFT3)
d_EAST_STRAIGHT3 = (d_EAST_RIGHT3, d_WEST_LEFT3)
d_NORTH_STRAIGHT3 = (d_NORTH_RIGHT3, d_SOUTH_LEFT3)

d_WEST_RIGHT_TURN3 = turn_road(d_WEST_RIGHT3, d_SOUTH_LEFT3, TURN_RIGHT, n)
d_WEST_LEFT_TURN3 = turn_road(d_WEST_RIGHT3, d_NORTH_LEFT3, TURN_LEFT, n)

d_SOUTH_RIGHT_TURN3 = turn_road(d_SOUTH_RIGHT3, d_EAST_LEFT3, TURN_RIGHT, n)
d_SOUTH_LEFT_TURN3 = turn_road(d_SOUTH_RIGHT3, d_WEST_LEFT3, TURN_LEFT, n)

d_EAST_RIGHT_TURN3 = turn_road(d_EAST_RIGHT3, d_NORTH_LEFT3, TURN_RIGHT, n)
d_EAST_LEFT_TURN3 = turn_road(d_EAST_RIGHT3, d_SOUTH_LEFT3, TURN_LEFT, n)

d_NORTH_RIGHT_TURN3 = turn_road(d_NORTH_RIGHT3, d_WEST_LEFT3, TURN_RIGHT, n)
d_NORTH_LEFT_TURN3 = turn_road(d_NORTH_RIGHT3, d_EAST_LEFT3, TURN_LEFT, n)

# Trying fourth intersection to the right of the original one
o5 = ( 2*b + l, 0)

e_WEST_RIGHT_START = ( WEST_RIGHT_START[0], EAST_LEFT[1]+ o5[0] )
e_WEST_LEFT_START = ( WEST_LEFT_START[0], EAST_RIGHT[1]+ o5[0] )

e_SOUTH_RIGHT_START = ( SOUTH_RIGHT_START[0], SOUTH_RIGHT_START[1]+ o5[0] )
e_SOUTH_LEFT_START = ( SOUTH_LEFT_START[0], SOUTH_LEFT_START[1]+ o5[0] )

e_EAST_RIGHT_START = ( EAST_RIGHT_START[0], EAST_RIGHT_START[1]+ o5[0] )
e_EAST_LEFT_START = ( EAST_LEFT_START[0], EAST_LEFT_START[1]+ o5[0] )

e_NORTH_RIGHT_START = ( NORTH_RIGHT_START[0], NORTH_RIGHT_START[1]+ o5[0] )
e_NORTH_LEFT_START = ( NORTH_LEFT_START[0], NORTH_LEFT_START[1]+ o5[0] )

e_WEST_RIGHT = ( WEST_RIGHT[0], EAST_LEFT_START[1]+ o5[0] )
e_WEST_LEFT = ( WEST_LEFT[0], EAST_RIGHT_START[1]+ o5[0] )

e_SOUTH_RIGHT = ( SOUTH_RIGHT[0], SOUTH_RIGHT[1]+ o5[0] )
e_SOUTH_LEFT = ( SOUTH_LEFT[0], SOUTH_LEFT[1]+ o5[0] )

e_EAST_RIGHT = ( EAST_RIGHT[0], EAST_RIGHT[1]+ o5[0] )
e_EAST_LEFT = ( EAST_LEFT[0], EAST_LEFT[1]+ o5[0] )

e_NORTH_RIGHT = ( NORTH_RIGHT[0], NORTH_LEFT[1]+ o5[0] )
e_NORTH_LEFT = ( NORTH_LEFT[0], NORTH_LEFT[1]+ o5[0] )

e_WEST_RIGHT_START2 = (e_WEST_RIGHT_START[0], e_WEST_RIGHT_START[1] - 4)
e_WEST_LEFT_START2 = (e_WEST_LEFT_START[0], e_WEST_LEFT_START[1] + 4)

e_SOUTH_RIGHT_START2 = (e_SOUTH_RIGHT_START[0] - 4, e_SOUTH_RIGHT_START[1])
e_SOUTH_LEFT_START2 = (e_SOUTH_LEFT_START[0] + 4, e_SOUTH_LEFT_START[1])

e_EAST_RIGHT_START2 = (e_EAST_RIGHT_START[0], e_EAST_RIGHT_START[1] + 4)
e_EAST_LEFT_START2 = (e_EAST_LEFT_START[0], e_EAST_LEFT_START[1] - 4)

e_NORTH_RIGHT_START2 = (e_NORTH_RIGHT_START[0] + 4, e_NORTH_RIGHT_START[1])
e_NORTH_LEFT_START2 = (e_NORTH_LEFT_START[0] - 4, e_NORTH_LEFT_START[1])

e_WEST_RIGHT_START3 = (e_WEST_RIGHT_START[0], e_WEST_RIGHT_START[1] - 8)
e_WEST_LEFT_START3 = (e_WEST_LEFT_START[0], e_WEST_LEFT_START[1] + 8)

e_SOUTH_RIGHT_START3 = (e_SOUTH_RIGHT_START[0] - 8, e_SOUTH_RIGHT_START[1])
e_SOUTH_LEFT_START3 = (e_SOUTH_LEFT_START[0] + 8, e_SOUTH_LEFT_START[1])

e_EAST_RIGHT_START3 = (e_EAST_RIGHT_START[0], e_EAST_RIGHT_START[1] + 8)
e_EAST_LEFT_START3 = (e_EAST_LEFT_START[0], e_EAST_LEFT_START[1] - 8)

e_NORTH_RIGHT_START3 = (e_NORTH_RIGHT_START[0] + 8, e_NORTH_RIGHT_START[1])
e_NORTH_LEFT_START3 = (e_NORTH_LEFT_START[0] - 8, e_NORTH_LEFT_START[1])

e_WEST_RIGHT2 = (e_WEST_RIGHT[0], e_WEST_RIGHT[1] - 4)
e_WEST_LEFT2 =	(e_WEST_LEFT[0], e_WEST_LEFT[1] + 4)

e_SOUTH_RIGHT2 = (e_SOUTH_RIGHT[0] - 4, e_SOUTH_RIGHT[1])
e_SOUTH_LEFT2 = (e_SOUTH_LEFT[0] + 4, e_SOUTH_LEFT[1])

e_EAST_RIGHT2 = (e_EAST_RIGHT[0], e_EAST_RIGHT[1] + 4)
e_EAST_LEFT2 = (e_EAST_LEFT[0], e_EAST_LEFT[1] - 4)

e_NORTH_RIGHT2 = (e_NORTH_RIGHT[0] + 4, e_NORTH_RIGHT[1])
e_NORTH_LEFT2 = (e_NORTH_LEFT[0] - 4, e_NORTH_LEFT[1])

e_WEST_RIGHT3 = (e_WEST_RIGHT[0], e_WEST_RIGHT[1] - 8)
e_WEST_LEFT3 =	(e_WEST_LEFT[0], e_WEST_LEFT[1] + 8)

e_SOUTH_RIGHT3 = (e_SOUTH_RIGHT[0] - 8, e_SOUTH_RIGHT[1])
e_SOUTH_LEFT3 = (e_SOUTH_LEFT[0] + 8, e_SOUTH_LEFT[1])

e_EAST_RIGHT3 = (e_EAST_RIGHT[0], e_EAST_RIGHT[1] + 8)
e_EAST_LEFT3 = (e_EAST_LEFT[0], e_EAST_LEFT[1] - 8)

e_NORTH_RIGHT3 = (e_NORTH_RIGHT[0] + 8, e_NORTH_RIGHT[1])
e_NORTH_LEFT3 = (e_NORTH_LEFT[0] - 8, e_NORTH_LEFT[1])

# Intersection e - Roads
e_WEST_INBOUND = (e_WEST_RIGHT_START, e_WEST_RIGHT)
e_SOUTH_INBOUND = (e_SOUTH_RIGHT_START, e_SOUTH_RIGHT)
e_EAST_INBOUND = (e_EAST_RIGHT_START, e_EAST_RIGHT)
e_NORTH_INBOUND = (e_NORTH_RIGHT_START, e_NORTH_RIGHT)

e_WEST_OUTBOUND = (e_WEST_LEFT, e_WEST_LEFT_START)
e_SOUTH_OUTBOUND = (e_SOUTH_LEFT, e_SOUTH_LEFT_START)
e_EAST_OUTBOUND = (e_EAST_LEFT, e_EAST_LEFT_START)
e_NORTH_OUTBOUND = (e_NORTH_LEFT, e_NORTH_LEFT_START)

e_WEST_STRAIGHT = (e_WEST_RIGHT, e_EAST_LEFT)
e_SOUTH_STRAIGHT = (e_SOUTH_RIGHT, e_NORTH_LEFT)
e_EAST_STRAIGHT = (e_EAST_RIGHT, e_WEST_LEFT)
e_NORTH_STRAIGHT = (e_NORTH_RIGHT, e_SOUTH_LEFT)

e_WEST_RIGHT_TURN = turn_road(e_WEST_RIGHT, e_SOUTH_LEFT, TURN_RIGHT, n)
e_WEST_LEFT_TURN = turn_road(e_WEST_RIGHT, e_NORTH_LEFT, TURN_LEFT, n)

e_SOUTH_RIGHT_TURN = turn_road(e_SOUTH_RIGHT, e_EAST_LEFT, TURN_RIGHT, n)
e_SOUTH_LEFT_TURN = turn_road(e_SOUTH_RIGHT, e_WEST_LEFT, TURN_LEFT, n)

e_EAST_RIGHT_TURN = turn_road(e_EAST_RIGHT, e_NORTH_LEFT, TURN_RIGHT, n)
e_EAST_LEFT_TURN = turn_road(e_EAST_RIGHT, e_SOUTH_LEFT, TURN_LEFT, n)

e_NORTH_RIGHT_TURN = turn_road(e_NORTH_RIGHT, e_WEST_LEFT, TURN_RIGHT, n)
e_NORTH_LEFT_TURN = turn_road(e_NORTH_RIGHT, e_EAST_LEFT, TURN_LEFT, n)

e_WEST_INBOUND2 = (e_WEST_RIGHT_START2, e_WEST_RIGHT2)
e_SOUTH_INBOUND2 = (e_SOUTH_RIGHT_START2, e_SOUTH_RIGHT2)
e_EAST_INBOUND2 = (e_EAST_RIGHT_START2, e_EAST_RIGHT2)
e_NORTH_INBOUND2 = (e_NORTH_RIGHT_START2, e_NORTH_RIGHT2)

e_WEST_OUTBOUND2 = (e_WEST_LEFT2, e_WEST_LEFT_START2)
e_SOUTH_OUTBOUND2 = (e_SOUTH_LEFT2, e_SOUTH_LEFT_START2)
e_EAST_OUTBOUND2 = (e_EAST_LEFT2, e_EAST_LEFT_START2)
e_NORTH_OUTBOUND2 = (e_NORTH_LEFT2, e_NORTH_LEFT_START2)

e_WEST_STRAIGHT2 = (e_WEST_RIGHT2, e_EAST_LEFT2)
e_SOUTH_STRAIGHT2 = (e_SOUTH_RIGHT2, e_NORTH_LEFT2)
e_EAST_STRAIGHT2 = (e_EAST_RIGHT2, e_WEST_LEFT2)
e_NORTH_STRAIGHT2 = (e_NORTH_RIGHT2, e_SOUTH_LEFT2)

e_WEST_RIGHT_TURN2 = turn_road(e_WEST_RIGHT2, e_SOUTH_LEFT2, TURN_RIGHT, n)
e_WEST_LEFT_TURN2 = turn_road(e_WEST_RIGHT2, e_NORTH_LEFT2, TURN_LEFT, n)

e_SOUTH_RIGHT_TURN2 = turn_road(e_SOUTH_RIGHT2, e_EAST_LEFT2, TURN_RIGHT, n)
e_SOUTH_LEFT_TURN2 = turn_road(e_SOUTH_RIGHT2, e_WEST_LEFT2, TURN_LEFT, n)

e_EAST_RIGHT_TURN2 = turn_road(e_EAST_RIGHT2, e_NORTH_LEFT2, TURN_RIGHT, n)
e_EAST_LEFT_TURN2 = turn_road(e_EAST_RIGHT2, e_SOUTH_LEFT2, TURN_LEFT, n)

e_NORTH_RIGHT_TURN2 = turn_road(e_NORTH_RIGHT2, e_WEST_LEFT2, TURN_RIGHT, n)
e_NORTH_LEFT_TURN2 = turn_road(e_NORTH_RIGHT2, e_EAST_LEFT2, TURN_LEFT, n)

e_WEST_INBOUND3 = (e_WEST_RIGHT_START3, e_WEST_RIGHT3)
e_SOUTH_INBOUND3 = (e_SOUTH_RIGHT_START3, e_SOUTH_RIGHT3)
e_EAST_INBOUND3 = (e_EAST_RIGHT_START3, e_EAST_RIGHT3)
e_NORTH_INBOUND3 = (e_NORTH_RIGHT_START3, e_NORTH_RIGHT3)

e_WEST_OUTBOUND3 = (e_WEST_LEFT3, e_WEST_LEFT_START3)
e_SOUTH_OUTBOUND3 = (e_SOUTH_LEFT3, e_SOUTH_LEFT_START3)
e_EAST_OUTBOUND3 = (e_EAST_LEFT3, e_EAST_LEFT_START3)
e_NORTH_OUTBOUND3 = (e_NORTH_LEFT3, e_NORTH_LEFT_START3)

e_WEST_STRAIGHT3 = (e_WEST_RIGHT3, e_EAST_LEFT3)
e_SOUTH_STRAIGHT3 = (e_SOUTH_RIGHT3, e_NORTH_LEFT3)
e_EAST_STRAIGHT3 = (e_EAST_RIGHT3, e_WEST_LEFT3)
e_NORTH_STRAIGHT3 = (e_NORTH_RIGHT3, e_SOUTH_LEFT3)

e_WEST_RIGHT_TURN3 = turn_road(e_WEST_RIGHT3, e_SOUTH_LEFT3, TURN_RIGHT, n)
e_WEST_LEFT_TURN3 = turn_road(e_WEST_RIGHT3, e_NORTH_LEFT3, TURN_LEFT, n)

e_SOUTH_RIGHT_TURN3 = turn_road(e_SOUTH_RIGHT3, e_EAST_LEFT3, TURN_RIGHT, n)
e_SOUTH_LEFT_TURN3 = turn_road(e_SOUTH_RIGHT3, e_WEST_LEFT3, TURN_LEFT, n)

e_EAST_RIGHT_TURN3 = turn_road(e_EAST_RIGHT3, e_NORTH_LEFT3, TURN_RIGHT, n)
e_EAST_LEFT_TURN3 = turn_road(e_EAST_RIGHT3, e_SOUTH_LEFT3, TURN_LEFT, n)

e_NORTH_RIGHT_TURN3 = turn_road(e_NORTH_RIGHT3, e_WEST_LEFT3, TURN_RIGHT, n)
e_NORTH_LEFT_TURN3 = turn_road(e_NORTH_RIGHT3, e_EAST_LEFT3, TURN_LEFT, n)


sim.create_roads([
    WEST_INBOUND,   #0
    SOUTH_INBOUND,  #1
    EAST_INBOUND,   #2
    NORTH_INBOUND,  #3

    WEST_OUTBOUND,  #4
    SOUTH_OUTBOUND, #5
    EAST_OUTBOUND,  #6
    NORTH_OUTBOUND, #7

    WEST_STRAIGHT,  #8
    SOUTH_STRAIGHT, #9
    EAST_STRAIGHT,  #10
    NORTH_STRAIGHT, #11

    WEST_INBOUND2,  #12
    SOUTH_INBOUND2, #13
    EAST_INBOUND2,  #14
    NORTH_INBOUND2, #15

    WEST_OUTBOUND2, #16
    SOUTH_OUTBOUND2, #17
    EAST_OUTBOUND2, #18
    NORTH_OUTBOUND2, #19

    WEST_STRAIGHT2, #20
    SOUTH_STRAIGHT2, #21
    EAST_STRAIGHT2, #22
    NORTH_STRAIGHT2, #23

    WEST_INBOUND3,  #24
    SOUTH_INBOUND3, #25
    EAST_INBOUND3,  #26
    NORTH_INBOUND3, #27

    WEST_OUTBOUND3, #28
    SOUTH_OUTBOUND3, #29
    EAST_OUTBOUND3, #30
    NORTH_OUTBOUND3, #31

    WEST_STRAIGHT3, #32
    SOUTH_STRAIGHT3, #33
    EAST_STRAIGHT3, #34
    NORTH_STRAIGHT3, #35

    *WEST_RIGHT_TURN, #36
    *WEST_LEFT_TURN, #56

    *SOUTH_RIGHT_TURN, #76
    *SOUTH_LEFT_TURN, #96

    *EAST_RIGHT_TURN, #116
    *EAST_LEFT_TURN, #136

    *NORTH_RIGHT_TURN, #156
    *NORTH_LEFT_TURN, #176

    *WEST_RIGHT_TURN2, #196
    *WEST_LEFT_TURN2, #216

    *SOUTH_RIGHT_TURN2, #236
    *SOUTH_LEFT_TURN2, #256

    *EAST_RIGHT_TURN2, #276
    *EAST_LEFT_TURN2, #296

    *NORTH_RIGHT_TURN2, #316
    *NORTH_LEFT_TURN2, #336

    *WEST_RIGHT_TURN3, #356
    *WEST_LEFT_TURN3, #376

    *SOUTH_RIGHT_TURN3, #396
    *SOUTH_LEFT_TURN3, #416

    *EAST_RIGHT_TURN3, #436
    *EAST_LEFT_TURN3, #456

    *NORTH_RIGHT_TURN3, #476
    *NORTH_LEFT_TURN3, #496

    b_WEST_INBOUND, #516
    b_SOUTH_INBOUND, #517
    b_EAST_INBOUND, #518
    b_NORTH_INBOUND, #519

    b_WEST_OUTBOUND, #520
    b_SOUTH_OUTBOUND, #521
    b_EAST_OUTBOUND, #522
    b_NORTH_OUTBOUND, #523

    b_WEST_STRAIGHT, #524
    b_SOUTH_STRAIGHT, #525
    b_EAST_STRAIGHT, #526
    b_NORTH_STRAIGHT, #527

    b_WEST_INBOUND2, #528
    b_SOUTH_INBOUND2, #529
    b_EAST_INBOUND2, #530
    b_NORTH_INBOUND2, #531

    b_WEST_OUTBOUND2, #532
    b_SOUTH_OUTBOUND2, #533
    b_EAST_OUTBOUND2, #534
    b_NORTH_OUTBOUND2, #535

    b_WEST_STRAIGHT2, #536
    b_SOUTH_STRAIGHT2, #537
    b_EAST_STRAIGHT2, #538
    b_NORTH_STRAIGHT2, #539

    b_WEST_INBOUND3, #540
    b_SOUTH_INBOUND3, #541
    b_EAST_INBOUND3, #542
    b_NORTH_INBOUND3, #543

    b_WEST_OUTBOUND3, #544
    b_SOUTH_OUTBOUND3, #545
    b_EAST_OUTBOUND3, #546
    b_NORTH_OUTBOUND3, #547

    b_WEST_STRAIGHT3, #548
    b_SOUTH_STRAIGHT3, #549
    b_EAST_STRAIGHT3, #550
    b_NORTH_STRAIGHT3, #551

    c_WEST_INBOUND, #552
    c_SOUTH_INBOUND, #553
    c_EAST_INBOUND, #554
    c_NORTH_INBOUND, #555

    c_WEST_OUTBOUND, #556
    c_SOUTH_OUTBOUND, #557
    c_EAST_OUTBOUND, #558
    c_NORTH_OUTBOUND, #559

    c_WEST_STRAIGHT, #560
    c_SOUTH_STRAIGHT, #561
    c_EAST_STRAIGHT, #562
    c_NORTH_STRAIGHT, #563

    c_WEST_INBOUND2, #564
    c_SOUTH_INBOUND2, #565
    c_EAST_INBOUND2, #566
    c_NORTH_INBOUND2, #567

    c_WEST_OUTBOUND2, #568
    c_SOUTH_OUTBOUND2, #569
    c_EAST_OUTBOUND2, #570
    c_NORTH_OUTBOUND2, #571

    c_WEST_STRAIGHT2, #572
    c_SOUTH_STRAIGHT2, #573
    c_EAST_STRAIGHT2, #574
    c_NORTH_STRAIGHT2, #575

    c_WEST_INBOUND3, #576
    c_SOUTH_INBOUND3, #577
    c_EAST_INBOUND3, #578
    c_NORTH_INBOUND3, #579

    c_WEST_OUTBOUND3, #580
    c_SOUTH_OUTBOUND3, #581
    c_EAST_OUTBOUND3, #582
    c_NORTH_OUTBOUND3, #583

    c_WEST_STRAIGHT3, #584
    c_SOUTH_STRAIGHT3, #585
    c_EAST_STRAIGHT3, #586
    c_NORTH_STRAIGHT3, #587

    d_WEST_INBOUND,  #588
    d_SOUTH_INBOUND,  #589
    d_EAST_INBOUND,  #590
    d_NORTH_INBOUND, #591

    d_WEST_OUTBOUND,  #592
    d_SOUTH_OUTBOUND,  #593
    d_EAST_OUTBOUND,  #594
    d_NORTH_OUTBOUND, #595

    d_WEST_STRAIGHT,  #596
    d_SOUTH_STRAIGHT,  #597
    d_EAST_STRAIGHT,  #598
    d_NORTH_STRAIGHT, #599

    d_WEST_INBOUND2,  #600
    d_SOUTH_INBOUND2,  #601
    d_EAST_INBOUND2,  #602
    d_NORTH_INBOUND2, #603

    d_WEST_OUTBOUND2,  #604
    d_SOUTH_OUTBOUND2,  #605
    d_EAST_OUTBOUND2,  #606
    d_NORTH_OUTBOUND2, #607

    d_WEST_STRAIGHT2,  #608
    d_SOUTH_STRAIGHT2,  #609
    d_EAST_STRAIGHT2,  #610
    d_NORTH_STRAIGHT2, #611

    d_WEST_INBOUND3,  #612
    d_SOUTH_INBOUND3,  #613
    d_EAST_INBOUND3,  #614
    d_NORTH_INBOUND3, #615

    d_WEST_OUTBOUND3,  #616
    d_SOUTH_OUTBOUND3,  #617
    d_EAST_OUTBOUND3,  #618
    d_NORTH_OUTBOUND3, #619

    d_WEST_STRAIGHT3, #620
    d_SOUTH_STRAIGHT3, #621
    d_EAST_STRAIGHT3, #622
    d_NORTH_STRAIGHT3, #623

    e_WEST_INBOUND,  # 624
    e_SOUTH_INBOUND,  # 625
    e_EAST_INBOUND,  # 626
    e_NORTH_INBOUND,  # 627

    e_WEST_OUTBOUND,  # 628
    e_SOUTH_OUTBOUND,  # 629
    e_EAST_OUTBOUND,  # 630
    e_NORTH_OUTBOUND,  # 631

    e_WEST_STRAIGHT,  # 632
    e_SOUTH_STRAIGHT,  # 633
    e_EAST_STRAIGHT,  # 634
    e_NORTH_STRAIGHT,  # 635

    e_WEST_INBOUND2,  # 636
    e_SOUTH_INBOUND2,  # 637
    e_EAST_INBOUND2,  # 638
    e_NORTH_INBOUND2,  # 639

    e_WEST_OUTBOUND2,  # 640
    e_SOUTH_OUTBOUND2,  # 641
    e_EAST_OUTBOUND2,  # 642
    e_NORTH_OUTBOUND2,  # 643

    e_WEST_STRAIGHT2,  # 644
    e_SOUTH_STRAIGHT2,  # 645
    e_EAST_STRAIGHT2,  # 646
    e_NORTH_STRAIGHT2,  # 647

    e_WEST_INBOUND3,  # 648
    e_SOUTH_INBOUND3,  # 649
    e_EAST_INBOUND3,  # 650
    e_NORTH_INBOUND3,  # 651

    e_WEST_OUTBOUND3,  # 652
    e_SOUTH_OUTBOUND3,  # 653
    e_EAST_OUTBOUND3,  # 654
    e_NORTH_OUTBOUND3,  # 655

    e_WEST_STRAIGHT3,  # 656
    e_SOUTH_STRAIGHT3,  # 657
    e_EAST_STRAIGHT3,  # 658
    e_NORTH_STRAIGHT3,  # 659

    *b_WEST_RIGHT_TURN,  # 660
    *b_WEST_LEFT_TURN,  # 680

    *b_SOUTH_RIGHT_TURN,  # 700
    *b_SOUTH_LEFT_TURN,  # 720

    *b_EAST_RIGHT_TURN,  # 740
    *b_EAST_LEFT_TURN,  # 760

    *b_NORTH_RIGHT_TURN,  # 780
    *b_NORTH_LEFT_TURN,  # 800

    *b_WEST_RIGHT_TURN2,  # 820
    *b_WEST_LEFT_TURN2,  # 840

    *b_SOUTH_RIGHT_TURN2,  # 860
    *b_SOUTH_LEFT_TURN2,  # 880

    *b_EAST_RIGHT_TURN2,  # 900
    *b_EAST_LEFT_TURN2,  # 920

    *b_NORTH_RIGHT_TURN2,  # 940
    *b_NORTH_LEFT_TURN2,  # 960

    *b_WEST_RIGHT_TURN3,  # 980
    *b_WEST_LEFT_TURN3,  # 1000

    *b_SOUTH_RIGHT_TURN3,  # 1020
    *b_SOUTH_LEFT_TURN3,  # 1040

    *b_EAST_RIGHT_TURN3,  # 1060
    *b_EAST_LEFT_TURN3,  # 1080

    *b_NORTH_RIGHT_TURN3,  # 1100
    *b_NORTH_LEFT_TURN3,  # 1120

    *c_WEST_RIGHT_TURN,  # 1140
    *c_WEST_LEFT_TURN,  # 1160

    *c_SOUTH_RIGHT_TURN,  # 1180
    *c_SOUTH_LEFT_TURN,  # 1200

    *c_EAST_RIGHT_TURN,  # 1220
    *c_EAST_LEFT_TURN,  # 1240

    *c_NORTH_RIGHT_TURN,  # 1260
    *c_NORTH_LEFT_TURN,  # 1280

    *c_WEST_RIGHT_TURN2,  # 1300
    *c_WEST_LEFT_TURN2,  # 1320

    *c_SOUTH_RIGHT_TURN2,  # 1340
    *c_SOUTH_LEFT_TURN2,  # 1360

    *c_EAST_RIGHT_TURN2,  # 1380
    *c_EAST_LEFT_TURN2,  # 1400

    *c_NORTH_RIGHT_TURN2,  # 1420
    *c_NORTH_LEFT_TURN2,  # 1440

    *c_WEST_RIGHT_TURN3,  # 1460
    *c_WEST_LEFT_TURN3,  # 1480

    *c_SOUTH_RIGHT_TURN3,  # 1500
    *c_SOUTH_LEFT_TURN3,  # 1520

    *c_EAST_RIGHT_TURN3,  # 1540
    *c_EAST_LEFT_TURN3,  # 1560

    *c_NORTH_RIGHT_TURN3,  # 1580
    *c_NORTH_LEFT_TURN3,  # 1600

    *d_WEST_RIGHT_TURN,  # 1620
    *d_WEST_LEFT_TURN,  # 1640

    *d_EAST_RIGHT_TURN,  # 1660
    *d_EAST_LEFT_TURN,  # 1680

    *d_SOUTH_RIGHT_TURN,  # 1700
    *d_SOUTH_LEFT_TURN,  # 1720

    *d_NORTH_RIGHT_TURN,  # 1740
    *d_NORTH_LEFT_TURN,  # 1760

    *d_WEST_RIGHT_TURN2,  # 1780
    *d_WEST_LEFT_TURN2,  # 1800

    *d_SOUTH_RIGHT_TURN2,  # 1820
    *d_SOUTH_LEFT_TURN2,  # 1840

    *d_EAST_RIGHT_TURN2,  # 1860
    *d_EAST_LEFT_TURN2,  # 1880

    *d_NORTH_RIGHT_TURN2,  # 1900
    *d_NORTH_LEFT_TURN2,  # 1920

    *d_WEST_RIGHT_TURN3,  # 1940
    *d_WEST_LEFT_TURN3,  # 1960

    *d_SOUTH_RIGHT_TURN3,  # 1980
    *d_SOUTH_LEFT_TURN3,  # 2000

    *d_EAST_RIGHT_TURN3,  # 2020
    *d_EAST_LEFT_TURN3,  # 2040

    *d_NORTH_RIGHT_TURN3,  # 2060
    *d_NORTH_LEFT_TURN3,  # 2080

    *e_WEST_RIGHT_TURN,  # 2100
    *e_WEST_LEFT_TURN,  # 2120

    *e_EAST_RIGHT_TURN,  # 2140
    *e_EAST_LEFT_TURN,  # 2160

    *e_SOUTH_RIGHT_TURN,  # 2180
    *e_SOUTH_LEFT_TURN,  # 2200

    *e_NORTH_RIGHT_TURN,  # 2220
    *e_NORTH_LEFT_TURN,  # 2240

    *e_WEST_RIGHT_TURN2,  # 2260
    *e_WEST_LEFT_TURN2,  # 2280

    *e_SOUTH_RIGHT_TURN2,  # 2300
    *e_SOUTH_LEFT_TURN2,  # 2320

    *e_EAST_RIGHT_TURN2,  # 2340
    *e_EAST_LEFT_TURN2,  # 2360

    *e_NORTH_RIGHT_TURN2,  # 2380
    *e_NORTH_LEFT_TURN2,  # 2400

    *e_WEST_RIGHT_TURN3,  # 2420
    *e_WEST_LEFT_TURN3,  # 2440

    *e_SOUTH_RIGHT_TURN3,  # 2460
    *e_SOUTH_LEFT_TURN3,  # 2480

    *e_EAST_RIGHT_TURN3,  # 2500
    *e_EAST_LEFT_TURN3,  # 2520

    *e_NORTH_RIGHT_TURN3,  # 2540
    *e_NORTH_LEFT_TURN3,  # 2560

])

def road(a): return range(a, a+n)

sim.create_gen({
    'vehicle_rate': VEHICLE_RATE,
    'vehicles': [
        # West to South, East, North
        [1, {'path': [0, *road(36), 5]}],
        [2, {'path': [0, *road(36), 6]}],
        [3, {'path': [0, *road(36), 7]}],

        # West_INBOUND2 to South_OUTBOUND2, East_OUTBOUND2, North_OUTBOUND2
        [1, {'path': [12, *road(36), 17]}],
        [2, {'path': [12, *road(36), 18]}],
        [3, {'path': [12, *road(36), 19]}],

        # NORTH_INBOUND3 to SOUTH_OUTBOUND3, EAST_OUTBOUND3, NORTH_OUTBOUND3
        [1, {'path': [24, *road(36), 29]}],
        [2, {'path': [24, *road(36), 30]}],
        [3, {'path': [24, *road(36), 31]}],

        # Similarly for other directions
        [0, {'path': [4, *road(36), 9]}],  # South to West, East, North
        [2, {'path': [4, *road(36), 10]}],
        [3, {'path': [4, *road(36), 11]}],

        [0, {'path': [16, *road(36), 21]}],  # SOUTH_INBOUND2 to WEST_OUTBOUND2, EAST_OUTBOUND2, NORTH_OUTBOUND2
        [2, {'path': [16, *road(36), 22]}],
        [3, {'path': [16, *road(36), 23]}],

        [0, {'path': [28, *road(36), 33]}],  # SOUTH_INBOUND3 to WEST_OUTBOUND3, EAST_OUTBOUND3, NORTH_OUTBOUND3
        [2, {'path': [28, *road(36), 34]}],
        [3, {'path': [28, *road(36), 35]}],

        [2, {'path': [6, *road(36), 1]}],  # East to South, West, North
        [0, {'path': [6, *road(36), 4]}],
        [3, {'path': [6, *road(36), 3]}],

        [2, {'path': [18, *road(36), 13]}],  # EAST_INBOUND2 to SOUTH_OUTBOUND, WEST_OUTBOUND, NORTH_OUTBOUND
        [0, {'path': [18, *road(36), 12]}],
        [3, {'path': [18, *road(36), 15]}],

        [2, {'path': [30, *road(36), 25]}],  # EAST_INBOUND3 to SOUTH_OUTBOUND3, WEST_OUTBOUND3, NORTH_OUTBOUND3
        [0, {'path': [30, *road(36), 24]}],
        [3, {'path': [30, *road(36), 27]}],

        [3, {'path': [7, *road(36), 2]}],  # North to South, East, West
        [1, {'path': [7, *road(36), 1]}],
        [2, {'path': [7, *road(36), 0]}],

        [3, {'path': [19, *road(36), 14]}],  # NORTH_INBOUND2 to SOUTH_OUTBOUND2, EAST_OUTBOUND2, WEST_OUTBOUND2
        [1, {'path': [19, *road(36), 13]}],
        [2, {'path': [19, *road(36), 16]}],

        [3, {'path': [31, *road(36), 26]}],  # NORTH_INBOUND3 to SOUTH_OUTBOUND3, EAST_OUTBOUND3, WEST_OUTBOUND3
        [1, {'path': [31, *road(36), 25]}],
        [2, {'path': [31, *road(36), 28]}],

        [1, {'path': [516, *road(36), 521]}],  # b_WEST_INBOUND to b_SOUTH_OUTBOUND, b_EAST_OUTBOUND, b_NORTH_OUTBOUND
        [2, {'path': [516, *road(36), 522]}],
        [3, {'path': [516, *road(36), 523]}],

        [1, {'path': [528, *road(36), 533]}],  # b_WEST_INBOUND2 to b_SOUTH_OUTBOUND2, b_EAST_OUTBOUND2, b_NORTH_OUTBOUND2
        [2, {'path': [528, *road(36), 534]}],
        [3, {'path': [528, *road(36), 535]}],

        [1, {'path': [540, *road(36), 545]}],  # b_NORTH_INBOUND3 to b_SOUTH_OUTBOUND3, b_EAST_OUTBOUND3, b_NORTH_OUTBOUND3
        [2, {'path': [540, *road(36), 546]}],
        [3, {'path': [540, *road(36), 547]}],

        [0, {'path': [518, *road(36), 525]}],  # b_SOUTH_INBOUND to b_WEST_OUTBOUND, b_EAST_OUTBOUND, b_NORTH_OUTBOUND
        [2, {'path': [518, *road(36), 526]}],
        [3, {'path': [518, *road(36), 527]}],

        [0, {'path': [530, *road(36), 537]}],  # b_SOUTH_INBOUND2 to b_WEST_OUTBOUND2, b_EAST_OUTBOUND2, b_NORTH_OUTBOUND2
        [2, {'path': [530, *road(36), 538]}],
        [3, {'path': [530, *road(36), 539]}],

        [0, {'path': [542, *road(36), 549]}],  # b_SOUTH_INBOUND3 to b_WEST_OUTBOUND3, b_EAST_OUTBOUND3, b_NORTH_OUTBOUND3
        [2, {'path': [542, *road(36), 550]}],
        [3, {'path': [542, *road(36), 551]}],

        [2, {'path': [520, *road(36), 517]}],  # b_EAST_INBOUND to b_SOUTH_INBOUND, b_WEST_INBOUND, b_NORTH_INBOUND
        [0, {'path': [520, *road(36), 516]}],
        [3, {'path': [520, *road(36), 519]}],

        [2, {'path': [532, *road(36), 529]}],  # b_EAST_INBOUND2 to b_SOUTH_INBOUND2, b_WEST_INBOUND2, b_NORTH_INBOUND2
        [0, {'path': [532, *road(36), 528]}],
        [3, {'path': [532, *road(36), 531]}],

        [2, {'path': [544, *road(36), 541]}],  # b_EAST_INBOUND3 to b_SOUTH_INBOUND3, b_WEST_INBOUND3, b_NORTH_INBOUND3
        [0, {'path': [544, *road(36), 540]}],
        [3, {'path': [544, *road(36), 543]}],

        [3, {'path': [522, *road(36), 517]}],  # b_NORTH_INBOUND to b_SOUTH_INBOUND, b_WEST_INBOUND, b_EAST_INBOUND
        [1, {'path': [522, *road(36), 516]}],
        [2, {'path': [522, *road(36), 519]}],

        [3, {'path': [534, *road(36), 529]}],  # b_NORTH_INBOUND2 to b_SOUTH_INBOUND2, b_WEST_INBOUND2, b_EAST_INBOUND2
        [1, {'path': [534, *road(36), 528]}],
        [2, {'path': [534, *road(36), 531]}],

        [3, {'path': [546, *road(36), 541]}],  # b_NORTH_INBOUND3 to b_SOUTH_INBOUND3, b_WEST_INBOUND3, b_EAST_INBOUND3
        [1, {'path': [546, *road(36), 540]}],
        [2, {'path': [546, *road(36), 543]}],

        [3, {'path': [552, *road(36), 557]}],  # c_WEST_INBOUND to c_SOUTH_INBOUND, c_NORTH_INBOUND, c_EAST_INBOUND
        [1, {'path': [552, *road(36), 558]}],
        [2, {'path': [552, *road(36), 559]}],

        [3, {'path': [553, *road(36), 556]}],  # c_SOUTH_INBOUND to c_NORTH_INBOUND, c_WEST_INBOUND, c_EAST_INBOUND
        [1, {'path': [553, *road(36), 558]}],
        [2, {'path': [553, *road(36), 559]}],

        [3, {'path': [554, *road(36), 557]}],  # c_EAST_INBOUND to c_SOUTH_INBOUND, c_WEST_INBOUND, c_NORTH_INBOUND
        [1, {'path': [554, *road(36), 556]}],
        [2, {'path': [554, *road(36), 559]}],

        [3, {'path': [555, *road(36), 557]}],  # c_NORTH_INBOUND to c_SOUTH_INBOUND, c_WEST_INBOUND, c_EAST_INBOUND
        [1, {'path': [555, *road(36), 558]}],
        [2, {'path': [555, *road(36), 556]}],

        [3, {'path': [564, *road(36), 569]}],  # c_WEST_INBOUND2 to c_SOUTH_INBOUND2, c_NORTH_INBOUND2, c_EAST_INBOUND2
        [1, {'path': [564, *road(36), 570]}],
        [2, {'path': [564, *road(36), 571]}],

        [3, {'path': [565, *road(36), 568]}],  # c_SOUTH_INBOUND2 to c_WEST_INBOUND2, c_NORTH_INBOUND2, c_EAST_INBOUND2
        [1, {'path': [565, *road(36), 570]}],
        [2, {'path': [565, *road(36), 571]}],

        [3, {'path': [567, *road(36), 569]}],  # c_EAST_INBOUND2 to c_SOUTH_INBOUND2, c_NORTH_INBOUND2, c_WEST_INBOUND2
        [1, {'path': [567, *road(36), 568]}],
        [2, {'path': [567, *road(36), 571]}],

        [3, {'path': [568, *road(36), 569]}],  # c_NORTH_INBOUND2 to c_SOUTH_INBOUND2, c_WEST_INBOUND2, c_EAST_INBOUND2
        [1, {'path': [568, *road(36), 570]}],
        [2, {'path': [568, *road(36), 568]}],

        [3, {'path': [576, *road(36), 581]}],  # c_NORTH_INBOUND3 to c_SOUTH_INBOUND3, c_WEST_INBOUND3, c_EAST_INBOUND3
        [1, {'path': [576, *road(36), 582]}],
        [2, {'path': [576, *road(36), 583]}],

        [3, {'path': [577, *road(36), 580]}],  # c_SOUTH_INBOUND3 to c_NORTH_INBOUND3, c_WEST_INBOUND3, c_EAST_INBOUND3
        [1, {'path': [577, *road(36), 582]}],
        [2, {'path': [577, *road(36), 583]}],

        [3, {'path': [578, *road(36), 581]}],  # c_EAST_INBOUND3 to c_SOUTH_INBOUND3, c_NORTH_INBOUND3, c_NORTH_INBOUND3
        [1, {'path': [578, *road(36), 580]}],
        [2, {'path': [578, *road(36), 583]}],

        [3, {'path': [579, *road(36), 581]}],  # c_NORTH_INBOUND3 to c_SOUTH_INBOUND3, c_WEST_INBOUND3, c_EAST_INBOUND3
        [1, {'path': [579, *road(36), 582]}],
        [2, {'path': [579, *road(36), 580]}],

        [3, {'path': [588, *road(36), 593]}],  # d_WEST_INBOUND to d_SOUTH_INBOUND, d_EAST_INBOUND, d_NORTH_INBOUND
        [2, {'path': [588, *road(36), 594]}],
        [1, {'path': [588, *road(36), 595]}],

        [3, {'path': [589, *road(36), 592]}],   # d_SOUTH_INBOUND to d_WEST_INBOUND, d_EAST_INBOUND, d_NORTH_INBOUND
        [2, {'path': [589, *road(36), 594]}],
        [1, {'path': [589, *road(36), 595]}],

        [3, {'path': [590, *road(36), 593]}],   # d_EAST_INBOUND to d_WEST_INBOUND, d_SOUTH_INBOUND, d_NORTH_INBOUND
        [2, {'path': [590, *road(36), 592]}],
        [1, {'path': [590, *road(36), 595]}],

        [3, {'path': [591, *road(36), 593]}],   # d_NORTH_INBOUND to d_WEST_INBOUND, d_SOUTH_INBOUND, d_EAST_INBOUND
        [2, {'path': [591, *road(36), 594]}],
        [1, {'path': [591, *road(36), 592]}],

        [3, {'path': [600, *road(36), 605]}],  # d_WEST_OUTBOUND2 to d_SOUTH_OUTBOUND2, d_EAST_OUTBOUND2, d_NORTH_OUTBOUND2
        [2, {'path': [600, *road(36), 606]}],
        [1, {'path': [600, *road(36), 607]}],

        [3, {'path': [601, *road(36), 604]}],   # d_SOUTH_OUTBOUND2 to d_WEST_OUTBOUND2, d_EAST_OUTBOUND2, d_NORTH_OUTBOUND2
        [2, {'path': [601, *road(36), 606]}],
        [1, {'path': [601, *road(36), 607]}],

        [3, {'path': [602, *road(36), 605]}],   # d_EAST_OUTBOUND2 to d_WEST_OUTBOUND2, d_SOUTH_OUTBOUND2, d_NORTH_OUTBOUND2
        [2, {'path': [602, *road(36), 604]}],
        [1, {'path': [602, *road(36), 607]}],

        [3, {'path': [603, *road(36), 605]}],   # d_NORTH_OUTBOUND2 to d_WEST_OUTBOUND2, d_SOUTH_OUTBOUND2, d_EAST_OUTBOUND2
        [2, {'path': [603, *road(36), 606]}],
        [1, {'path': [603, *road(36), 604]}],

        [3, {'path': [612, *road(36), 617]}],  # d_WEST_OUTBOUND3 to d_SOUTH_OUTBOUND3, d_EAST_OUTBOUND3, d_NORTH_OUTBOUND3
        [2, {'path': [612, *road(36), 618]}],
        [1, {'path': [612, *road(36), 619]}],

        [3, {'path': [613, *road(36), 616]}],   # d_SOUTH_OUTBOUND3 to d_WEST_OUTBOUND3, d_EAST_OUTBOUND3, d_NORTH_OUTBOUND3
        [2, {'path': [613, *road(36), 618]}],
        [1, {'path': [613, *road(36), 619]}],

        [3, {'path': [614, *road(36), 617]}],   # d_EAST_OUTBOUND3 to d_WEST_OUTBOUND3, d_SOUTH_OUTBOUND3, d_NORTH_OUTBOUND3
        [2, {'path': [614, *road(36), 616]}],
        [1, {'path': [614, *road(36), 619]}],

        [3, {'path': [615, *road(36), 617]}],   # d_NORTH_OUTBOUND3 to d_WEST_OUTBOUND3, d_SOUTH_OUTBOUND3, d_EAST_OUTBOUND3
        [2, {'path': [615, *road(36), 618]}],
        [1, {'path': [615, *road(36), 616]}],
        
        [3, {'path': [624, *road(36), 629]}],  # e_WEST_STRAIGHT to e_SOUTH_STRAIGHT, e_EAST_STRAIGHT, e_NORTH_STRAIGHT
        [2, {'path': [624, *road(36), 630]}],
        [1, {'path': [624, *road(36), 631]}],

        [3, {'path': [625, *road(36), 628]}],   # e_SOUTH_STRAIGHT to e_WEST_STRAIGHT, e_EAST_STRAIGHT, e_NORTH_STRAIGHT
        [2, {'path': [625, *road(36), 630]}],
        [1, {'path': [625, *road(36), 631]}],

        [3, {'path': [626, *road(36), 629]}],   # e_EAST_STRAIGHT to e_WEST_STRAIGHT, e_SOUTH_STRAIGHT, e_NORTH_STRAIGHT
        [2, {'path': [626, *road(36), 628]}],
        [1, {'path': [626, *road(36), 631]}],

        [3, {'path': [627, *road(36), 629]}],   # e_NORTH_STRAIGHT to e_WEST_STRAIGHT, e_SOUTH_STRAIGHT, e_EAST_STRAIGHT
        [2, {'path': [627, *road(36), 630]}],
        [1, {'path': [627, *road(36), 628]}],

        [3, {'path': [636, *road(36), 641]}],  # e_WEST_STRAIGHT2 to e_SOUTH_STRAIGHT2, e_EAST_STRAIGHT2, e_NORTH_STRAIGHT2
        [2, {'path': [636, *road(36), 642]}],
        [1, {'path': [636, *road(36), 643]}],

        [3, {'path': [637, *road(36), 640]}],   # e_SOUTH_STRAIGHT2 to e_WEST_STRAIGHT2, e_EAST_STRAIGHT2, e_NORTH_STRAIGHT2
        [2, {'path': [637, *road(36), 642]}],
        [1, {'path': [637, *road(36), 643]}],

        [3, {'path': [638, *road(36), 641]}],   # e_EAST_STRAIGHT2 to e_WEST_STRAIGHT2, e_SOUTH_STRAIGHT2, e_NORTH_STRAIGHT2
        [2, {'path': [638, *road(36), 640]}],
        [1, {'path': [638, *road(36), 643]}],

        [3, {'path': [639, *road(36), 641]}],   # e_NORTH_STRAIGHT2 to e_WEST_STRAIGHT2, e_SOUTH_STRAIGHT2, e_EAST_STRAIGHT2
        [2, {'path': [639, *road(36), 642]}],
        [1, {'path': [639, *road(36), 640]}],

        [3, {'path': [648, *road(36), 653]}],  # e_WEST_STRAIGHT3 to e_SOUTH_STRAIGHT3, e_EAST_STRAIGHT3, e_NORTH_STRAIGHT3
        [2, {'path': [648, *road(36), 654]}],
        [2, {'path': [648, *road(36), 655]}],

        [3, {'path': [649, *road(36), 652]}],   # e_SOUTH_STRAIGHT3 to e_WEST_STRAIGHT3, e_EAST_STRAIGHT3, e_NORTH_STRAIGHT3
        [2, {'path': [649, *road(36), 654]}],
        [1, {'path': [649, *road(36), 655]}],

        [3, {'path': [650, *road(36), 653]}],   # e_EAST_STRAIGHT3 to e_WEST_STRAIGHT3, e_SOUTH_STRAIGHT3, e_NORTH_STRAIGHT3
        [2, {'path': [650, *road(36), 652]}],
        [1, {'path': [650, *road(36), 655]}],

        [3, {'path': [651, *road(36), 653]}],   # e_NORTH_STRAIGHT3 to e_WEST_STRAIGHT3, e_SOUTH_STRAIGHT3, e_EAST_STRAIGHT3
        [2, {'path': [651, *road(36), 652]}],
        [1, {'path': [651, *road(36), 654]}],

    ]
})



sim.create_signal([[0], [1], [2], [3]])
sim.create_signal([[12], [13], [14], [15]])

# Create Green Light for 3rd Lane
sim.create_signal([[24]])
sim.create_signal([[25]])
sim.create_signal([[26]])
sim.create_signal([[27]])

sim.create_signal([[516], [517], [518], [519]])
sim.create_signal([[528], [529], [530], [531]])

sim.create_signal([[540]])
sim.create_signal([[541]])
sim.create_signal([[542]])
sim.create_signal([[543]])

sim.create_signal([[552], [553], [554], [555]])
sim.create_signal([[564], [565], [566], [567]])
sim.create_signal([[576], [577], [578], [579]])

sim.create_signal([[588], [589], [590], [591]])
sim.create_signal([[600], [601], [602], [603]])
sim.create_signal([[612], [613], [614], [615]])

sim.create_signal([[624], [625], [626], [627]])
sim.create_signal([[636], [637], [638], [639]])
sim.create_signal([[648], [649], [650], [651]])

# Start simulation
win = Window(sim)
win.zoom = 10
if(sim.isPaused == False):
    win.run(steps_per_update=STEPS_PER_UPDATE)